modLoader = "javafml"
loaderVersion = "[36,)"
license = "GNU GPLv3"

[[mods]]
modId = "reasurecraft"
version = "0.4"
displayName = "Reasure Craft"
credits = "Thanks for this tutorial mod goes to Java"
authors = "Reasure" #optional
description = '''
This is my first tutorial mod

Thanks for playing
'''

[[dependencies.reasurecraft]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.reasurecraft]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"

[[dependencies.reasurecraft]]
modId = "jei"
mandatory = false
versionRange = "[7.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.reasurecraft]]
modId = "waila"
mandatory = false
versionRange = "[1.10,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.reasurecraft]]
modId = "patchouli"
mandatory = false
versionRange = "[1.16-37,)"
ordering = "AFTER"
side = "BOTH"
