@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package reasure.reasurecraft.entities.projectiles;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;